# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'changer_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_value_changer_dialog(object):
    def setupUi(self, value_changer_dialog):
        value_changer_dialog.setObjectName("value_changer_dialog")
        value_changer_dialog.resize(424, 117)
        self.gridLayout = QtWidgets.QGridLayout(value_changer_dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.value_name_lbl = QtWidgets.QLabel(value_changer_dialog)
        self.value_name_lbl.setObjectName("value_name_lbl")
        self.gridLayout.addWidget(self.value_name_lbl, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(value_changer_dialog)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 1, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(value_changer_dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 2, 0, 1, 1)

        self.retranslateUi(value_changer_dialog)
        self.buttonBox.accepted.connect(value_changer_dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(value_changer_dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(value_changer_dialog)

    def retranslateUi(self, value_changer_dialog):
        _translate = QtCore.QCoreApplication.translate
        value_changer_dialog.setWindowTitle(_translate("value_changer_dialog", "Введи новое значение"))
        self.value_name_lbl.setText(_translate("value_changer_dialog", "TextLabel"))
