# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'changer_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_value_changer_dialog(object):
    def setupUi(self, value_changer_dialog):
        value_changer_dialog.setObjectName("value_changer_dialog")
        value_changer_dialog.resize(236, 117)
        self.formLayout = QtWidgets.QFormLayout(value_changer_dialog)
        self.formLayout.setObjectName("formLayout")
        self.value_name_lbl = QtWidgets.QLabel(value_changer_dialog)
        self.value_name_lbl.setObjectName("value_name_lbl")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.value_name_lbl)
        self.lineEdit = QtWidgets.QLineEdit(value_changer_dialog)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lineEdit)
        self.buttonBox = QtWidgets.QDialogButtonBox(value_changer_dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.buttonBox)

        self.retranslateUi(value_changer_dialog)
        self.buttonBox.accepted.connect(value_changer_dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(value_changer_dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(value_changer_dialog)

    def retranslateUi(self, value_changer_dialog):
        _translate = QtCore.QCoreApplication.translate
        value_changer_dialog.setWindowTitle(_translate("value_changer_dialog", "Введи новое значение"))
        self.value_name_lbl.setText(_translate("value_changer_dialog", "TextLabel"))
