# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'two_chanell.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.read1_btn = QtWidgets.QPushButton(self.centralwidget)
        self.read1_btn.setObjectName("read1_btn")
        self.gridLayout.addWidget(self.read1_btn, 0, 0, 1, 1)
        self.textBrowser_1 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_1.setObjectName("textBrowser_1")
        self.gridLayout.addWidget(self.textBrowser_1, 0, 1, 1, 1)
        self.send1_btn = QtWidgets.QPushButton(self.centralwidget)
        self.send1_btn.setObjectName("send1_btn")
        self.gridLayout.addWidget(self.send1_btn, 0, 2, 1, 1)
        self.read2_btn = QtWidgets.QPushButton(self.centralwidget)
        self.read2_btn.setObjectName("read2_btn")
        self.gridLayout.addWidget(self.read2_btn, 1, 0, 1, 1)
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.gridLayout.addWidget(self.textBrowser_2, 1, 1, 1, 1)
        self.send2_btn = QtWidgets.QPushButton(self.centralwidget)
        self.send2_btn.setObjectName("send2_btn")
        self.gridLayout.addWidget(self.send2_btn, 1, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.read1_btn.setText(_translate("MainWindow", "читать 1 канал"))
        self.send1_btn.setText(_translate("MainWindow", "отправить в 1 канал"))
        self.read2_btn.setText(_translate("MainWindow", "читать 2 канал"))
        self.send2_btn.setText(_translate("MainWindow", "отправить во 2 канал"))
