adc_inputs&discrete_outputs:
- description: lol
  editable: false
  index: 8528
  name: BRAKE_HYDRAULIC_ADC_STATUS_ACC_1
  sub_index: 1
  type: UNSIGNED16
- description: lol
  editable: false
  index: 8528
  name: BRAKE_HYDRAULIC_ADC_STATUS_WHEEL_1
  sub_index: 2
  type: UNSIGNED16
- description: lol
  editable: false
  index: 8528
  name: BRAKE_HYDRAULIC_ADC_STATUS_ACC_2
  sub_index: 3
  type: UNSIGNED16
- description: lol
  editable: false
  index: 8528
  name: BRAKE_HYDRAULIC_ADC_STATUS_WHEEL_2
  sub_index: 4
  type: UNSIGNED16
- description: lol
  editable: false
  index: 8521
  name: BRAKE_HYDRAULIC_ADC_RAW_ACC_1_MA
  sub_index: 1
  type: UNSIGNED32
- description: lol
  editable: false
  index: 8521
  name: BRAKE_HYDRAULIC_ADC_RAW_WHEEL_1_MA
  sub_index: 2
  type: UNSIGNED32
- description: lol
  editable: false
  index: 8521
  name: BRAKE_HYDRAULIC_ADC_RAW_ACC_2_MA
  sub_index: 3
  type: UNSIGNED32
- description: lol
  editable: false
  index: 8521
  name: BRAKE_HYDRAULIC_ADC_RAW_WHEEL_2_MA
  sub_index: 4
  type: UNSIGNED32
- description: lol
  editable: false
  index: 8561
  name: DO_STATE_HYDRAULIC_BRAKE_PUMP
  sub_index: 13
  type: UNSIGNED8
- description: lol
  editable: false
  index: 8562
  name: DO_ERROR_HYDRAULIC_BRAKE_PUMP
  sub_index: 13
  type: UNSIGNED16
- description: lol
  editable: true
  index: 8563
  name: DO_CMD_SERVICE_HYDRAULIC_BRAKE_PUMP
  sub_index: 13
  type: UNSIGNED8
brake_settings:
- description: lol
  editable: true
  index: 8519
  name: BRAKE_SMOOTH_PID_P_NUM
  sub_index: 2
  type: UNSIGNED16
- description: lol
  editable: true
  index: 8519
  name: BRAKE_SMOOTH_PID_P_DENOM
  sub_index: 3
  type: UNSIGNED16
- description: lol
  editable: true
  index: 8519
  name: BRAKE_SMOOTH_PID_I_NUM
  sub_index: 4
  type: UNSIGNED16
- description: lol
  editable: true
  index: 8519
  name: BRAKE_SMOOTH_PID_I_DENOM
  sub_index: 5
  type: UNSIGNED16
- description: lol
  editable: true
  index: 8519
  name: BRAKE_SMOOTH_PID_D_NUM
  sub_index: 6
  type: UNSIGNED16
- description: lol
  editable: true
  index: 8519
  name: BRAKE_SMOOTH_PID_D_DENOM
  sub_index: 7
  type: UNSIGNED16
- description: lol
  editable: true
  index: 8519
  name: BRAKE_SMOOTH_EMERGENCY_PERCENT
  sub_index: 8
  type: UNSIGNED8
- description: lol
  editable: true
  index: 8519
  name: BRAKE_SMOOTH_ACC_PR_FEED_THRES_MBAR
  sub_index: 9
  type: UNSIGNED32
- description: lol
  editable: true
  index: 8519
  name: BRAKE_SMOOTH_ACC_PR_RELIEVE_THRES_MBAR
  sub_index: 10
  type: UNSIGNED32
- description: lol
  editable: true
  index: 8519
  name: BRAKE_SMOOTH_MAX_WHEEL_PR_MBAR
  sub_index: 11
  type: UNSIGNED32
- description: lol
  editable: true
  index: 8520
  name: BRAKE_HYDRAULIC_VALVE_HSV_MIN_MV
  sub_index: 1
  type: UNSIGNED16
- description: lol
  editable: true
  index: 8520
  name: BRAKE_HYDRAULIC_VALVE_HSV_MAX_MV
  sub_index: 2
  type: UNSIGNED16
- description: lol
  editable: true
  index: 8520
  name: BRAKE_HYDRAULIC_VALVE_SV_MIN_MV
  sub_index: 3
  type: UNSIGNED16
- description: lol
  editable: true
  index: 8520
  name: BRAKE_HYDRAULIC_VALVE_SV_MAX_MV
  sub_index: 4
  type: UNSIGNED16
- description: lol
  editable: true
  index: 8520
  name: BRAKE_HYDRAULIC_VALVE_IV_MIN_MV
  sub_index: 5
  type: UNSIGNED16
- description: lol
  editable: true
  index: 8520
  name: BRAKE_HYDRAULIC_VALVE_IV_MAX_MV
  sub_index: 6
  type: UNSIGNED16
- description: lol
  editable: true
  index: 8520
  name: BRAKE_HYDRAULIC_P_FILTER_FACTOR
  sub_index: 7
  type: UNSIGNED8
common:
- description: lol> Запрос на чтение всех сохраненных параметров из энергонезависимой
    памяти. Для осуществления достаточно одного SDO на запись со значением "1". При
    чтении этого параметра отображается число выполненных соответствующих запросов
    с момента запуска КВУ.
  editable: true
  index: 8450
  name: EEPROM_READ_REQUEST
  sub_index: 1
  type: UNSIGNED32
- description: lol> Запрос на запись в энергонезависимую память текущих значений всех
    сохраняемых параметров. Для осуществления достаточно одного SDO на запись со значением
    "1". При чтении этого параметра отображается число выполненных соответствующих
    запросов с момента запуска КВУ.
  editable: true
  index: 8450
  name: EEPROM_WRITE_REQUEST
  sub_index: 2
  type: UNSIGNED32
- description: lolВключение ручного режима управления
  editable: true
  index: 8448
  name: MANUAL_CONTROL
  sub_index: 1
  type: UNSIGNED8
- description: lol> Включение сервисного режима работы следующих дискретных выходов
    КВУ
  editable: true
  index: 8448
  name: OUTPUTS_SERVICE_MODE
  sub_index: 3
  type: UNSIGNED8
- description: lolТип тормозной системы, которая используется на этой машине
  editable: true
  eeprom: true
  index: 8448
  name: BRAKES_TYPE
  sub_index: 4
  type: UNSIGNED8
  value_table:
    0: Отключено
    1: Дискретный тормоз
    2: Плавный тормоз
pwm_outputs:
- description: lol
  editable: false
  index: 8565
  name: PWM_ERROR_HYDRAULIC_BRAKE_HSV1
  sub_index: 1
  type: UNSIGNED16
- description: lol
  editable: false
  index: 8565
  name: PWM_ERROR_HYDRAULIC_BRAKE_SV1
  sub_index: 2
  type: UNSIGNED16
- description: lol
  editable: false
  index: 8565
  name: PWM_ERROR_HYDRAULIC_BRAKE_IV1
  sub_index: 3
  type: UNSIGNED16
- description: lol
  editable: false
  index: 8565
  name: PWM_ERROR_HYDRAULIC_BRAKE_HSV2
  sub_index: 4
  type: UNSIGNED16
- description: lol
  editable: false
  index: 8565
  name: PWM_ERROR_HYDRAULIC_BRAKE_SV2
  sub_index: 5
  type: UNSIGNED16
- description: lol
  editable: false
  index: 8565
  name: PWM_ERROR_HYDRAULIC_BRAKE_IV2
  sub_index: 6
  type: UNSIGNED16
- description: lol
  editable: true
  index: 8566
  name: PWM_CMD_SERVICE_HYDRAULIC_BRAKE_HSV1
  sub_index: 1
  type: UNSIGNED16
- description: lol
  editable: true
  index: 8566
  name: PWM_CMD_SERVICE_HYDRAULIC_BRAKE_SV1
  sub_index: 2
  type: UNSIGNED16
- description: lol
  editable: true
  index: 8566
  name: PWM_CMD_SERVICE_HYDRAULIC_BRAKE_IV1
  sub_index: 3
  type: UNSIGNED16
- description: lol
  editable: true
  index: 8566
  name: PWM_CMD_SERVICE_HYDRAULIC_BRAKE_HSV2
  sub_index: 4
  type: UNSIGNED16
- description: lol
  editable: true
  index: 8566
  name: PWM_CMD_SERVICE_HYDRAULIC_BRAKE_SV2
  sub_index: 5
  type: UNSIGNED16
- description: lol
  editable: true
  index: 8566
  name: PWM_CMD_SERVICE_HYDRAULIC_BRAKE_IV2
  sub_index: 6
  type: UNSIGNED16
- description: lol
  editable: false
  index: 8568
  name: PWM_STATE_HYDRAULIC_BRAKE_HSV1
  sub_index: 1
  type: UNSIGNED16
- description: lol
  editable: false
  index: 8568
  name: PWM_STATE_HYDRAULIC_BRAKE_SV1
  sub_index: 2
  type: UNSIGNED16
- description: lol
  editable: false
  index: 8568
  name: PWM_STATE_HYDRAULIC_BRAKE_IV1
  sub_index: 3
  type: UNSIGNED16
- description: lol
  editable: false
  index: 8568
  name: PWM_STATE_HYDRAULIC_BRAKE_HSV2
  sub_index: 4
  type: UNSIGNED16
- description: lol
  editable: false
  index: 8568
  name: PWM_STATE_HYDRAULIC_BRAKE_SV2
  sub_index: 5
  type: UNSIGNED16
- description: lol
  editable: false
  index: 8568
  name: PWM_STATE_HYDRAULIC_BRAKE_IV2
  sub_index: 6
  type: UNSIGNED16
smooth_brake_values&discrete_brake_values:
- description: lol
  editable: true
  index: 8519
  name: BRAKE_SMOOTH_MANUAL_STOP_CMD
  sub_index: 1
  type: UNSIGNED8
- description: lol
  editable: false
  index: 8519
  name: BRAKE_SMOOTH_CONT_1_STAGE
  sub_index: 12
  type: UNSIGNED8
- description: lol
  editable: false
  index: 8521
  name: BRAKE_HYDRAULIC_PRESSURE_ACC_1_MBAR
  sub_index: 5
  type: UNSIGNED32
- description: lol
  editable: false
  index: 8521
  name: BRAKE_HYDRAULIC_PRESSURE_WHEEL_1_MBAR
  sub_index: 6
  type: UNSIGNED32
- description: lol
  editable: false
  index: 8521
  name: BRAKE_HYDRAULIC_PRESSURE_ACC_2_MBAR
  sub_index: 7
  type: UNSIGNED32
- description: lol
  editable: false
  index: 8521
  name: BRAKE_HYDRAULIC_PRESSURE_WHEEL_2_MBAR
  sub_index: 8
  type: UNSIGNED32
- description: lol
  editable: true
  index: 8518
  name: BRAKE_DISCRETE_PUMP_TIMEOUT_MS
  sub_index: 1
  type: UNSIGNED16
- description: lol
  editable: true
  index: 8518
  name: BRAKE_DISCRETE_HOLD_TIMEOUT_MS
  sub_index: 2
  type: UNSIGNED16
- description: lol
  editable: true
  index: 8518
  name: BRAKE_DISCRETE_MANUAL_STOP_CMD
  sub_index: 3
  type: UNSIGNED8
